#!/usr/bin/env node
// Build pipeline for lily-design-system-web-components-headless.
//
// Two steps, in order:
//
//   1. Generate `index.ts` — the public barrel. Every component in
//      `components/` is re-exported by class name AND registered as a
//      custom element under its `lily-{slug}` tag name. The barrel is
//      GENERATED rather than hand-maintained for the same reason
//      react-headless's is: a hand-written list silently omits a newly
//      added component.
//
//   2. Bundle to `dist/` with tsup (ESM + .d.ts).
//
// The exported class name is DISCOVERED from each source file (the
// `export class Foo extends HTMLElement` declaration) rather than
// derived by string-casing the filename, so a file whose class name
// doesn't follow the mechanical kebab-to-Pascal mapping still builds
// correctly and a genuinely missing export fails loudly instead of
// silently emitting a broken import.

import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(fileURLToPath(import.meta.url));
const componentsDir = path.join(root, "components");

/** Source files that are components — not tests, not Storybook stories. */
function isComponentSource(name) {
    if (!name.endsWith(".ts")) return false;
    if (name.endsWith(".test.ts")) return false;
    if (name.includes(".stories.")) return false;
    return true;
}

const files = fs.readdirSync(componentsDir).filter(isComponentSource).sort();

if (files.length === 0) {
    throw new Error(`No component sources found in ${componentsDir}.`);
}

const lines = [];
const seenTags = new Map();
const seenClasses = new Map();

for (const file of files) {
    const slug = file.slice(0, -".ts".length);
    const source = fs.readFileSync(path.join(componentsDir, file), "utf8");
    const match = source.match(/^export class ([A-Za-z0-9_]+) extends HTMLElement/m);
    if (!match) {
        throw new Error(`${file}: no "export class X extends HTMLElement" declaration found.`);
    }
    const className = match[1];
    const tag = `lily-${slug}`;

    if (seenClasses.has(className)) {
        throw new Error(`Duplicate export "${className}": declared by both ${seenClasses.get(className)} and ${file}.`);
    }
    seenClasses.set(className, file);
    if (seenTags.has(tag)) {
        throw new Error(`Duplicate custom element tag "${tag}": declared by both ${seenTags.get(tag)} and ${file}.`);
    }
    seenTags.set(tag, file);

    lines.push(`export { ${className} } from "./components/${slug}.js";`);
    lines.push(`import { ${className} as _${className} } from "./components/${slug}.js";`);
    lines.push(`if (!customElements.get("${tag}")) customElements.define("${tag}", _${className});`);
    lines.push("");
}

fs.writeFileSync(
    path.join(root, "index.ts"),
    "// Generated by build.mjs — do not edit by hand.\n" +
        "// Barrel export + custom-element registration for every component in\n" +
        "// this partial catalog (see spec/index.md for scope).\n\n" +
        lines.join("\n") +
        "\n",
);
console.log(`generated index.ts (${files.length} components)`);

// Clean first, same reasoning as react-headless: a stale dist/ mixing
// artifacts from two different build configurations ships silently.
fs.rmSync(path.join(root, "dist"), { recursive: true, force: true });

execFileSync(
    "npx",
    ["tsup", "index.ts", "--format", "esm", "--dts", "--out-dir", "dist"],
    { cwd: root, stdio: "inherit" },
);

for (const artifact of ["index.js", "index.d.ts"]) {
    const file = path.join(root, "dist", artifact);
    if (!fs.existsSync(file) || fs.statSync(file).size === 0) {
        throw new Error(`expected a non-empty dist/${artifact} after build.`);
    }
}
console.log("build ok");
